name: versioning

on:
  pull_request:
    branches: [ master ]

jobs:
  versioning:
    name: Versioning
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: git-fetch
        run: |
          git fetch --prune --unshallow

      - name: set-tag-env
        run: |
          LAST_COMMIT=$(jq --raw-output .pull_request.title "$GITHUB_EVENT_PATH")
          touch ./.tag
          if VERSION=`git describe --abbrev=0 --tags` && [ ! -z "`git diff $VERSION`" -o -z "$VERSION" ]; then
            VERSION=${VERSION:-'0.0.0'}
            MAJOR="${VERSION%%.*}"; MAJOR="${MAJOR#v}"; VERSION="${VERSION#*.}"
            MINOR="${VERSION%%.*}"; VERSION="${VERSION#*.}"
            PATCH="${VERSION%%.*}"; VERSION="${VERSION#*.}"
            if echo $LAST_COMMIT | grep "\[\(major\|MAJOR\)\]" > /dev/null; then
              MAJOR=$((MAJOR+1))
              echo "v$MAJOR.0.0" > ./.tag
            elif echo $LAST_COMMIT | grep "\[\(minor\|MINOR\)\]" > /dev/null; then
              MINOR=$((MINOR+1))
              echo "v$MAJOR.$MINOR.0" > ./.tag
            elif echo $LAST_COMMIT | grep "\[\(patch\|PATCH\)\]" > /dev/null; then
              PATCH=$((PATCH+1))
              echo "v$MAJOR.$MINOR.$PATCH" > ./.tag
            fi
          else
            if echo $LAST_COMMIT | grep "\[\(major\|MAJOR\)\]" > /dev/null; then
              echo "v1.0.0" > ./.tag
            elif echo $LAST_COMMIT | grep "\[\(minor\|MINOR\)\]" > /dev/null; then
              echo "v0.1.0" > ./.tag
            elif echo $LAST_COMMIT | grep "\[\(patch\|PATCH\)\]" > /dev/null; then
              echo "v0.0.1" > ./.tag
            fi
          fi
          cat ./.tag
          echo "::set-output name=TAG::$(cat ./.tag)"
          echo "::set-env name=TAG::$(cat ./.tag)"
      - name: echo
        run: echo $TAG

      - name: Custom Github Status
        uses: geekodour/gh-actions-custom-status@v0.0.4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          LAST_COMMIT_SHA: ${{ github.event.client_payload.LAST_COMMIT_SHA }}
        with:
          args: >-
            --state=pending
            --context=foo-status-update
            --target_url=https://github.com/${{ github.repository }}/actions

      - name: cat
        run: echo cat "$GITHUB_EVENT_PATH"
