name: versioning

on:
  pull_request:
    branches: [ master ]

jobs:
  versioning:
    name: Versioning
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: check
        run: |
          git fetch --prune --unshallow
          LAST_COMMIT=$(jq --raw-output .pull_request.title "$GITHUB_EVENT_PATH")
          touch ./.tag
          if VERSION=`git describe --abbrev=0 --tags` && [ ! -z "`git diff $VERSION`" -o -z "$VERSION" ]; then
            VERSION=${VERSION:-'0.0.0'}
            MAJOR="${VERSION%%.*}"; MAJOR="${MAJOR#v}"; VERSION="${VERSION#*.}"
            MINOR="${VERSION%%.*}"; VERSION="${VERSION#*.}"
            PATCH="${VERSION%%.*}"; VERSION="${VERSION#*.}"
            if echo $LAST_COMMIT | grep "\[\(major\|MAJOR\)\]" > /dev/null; then
              MAJOR=$((MAJOR+1))
              echo "v$MAJOR.0.0" > ./.tag
            elif echo $LAST_COMMIT | grep "\[\(minor\|MINOR\)\]" > /dev/null; then
              MINOR=$((MINOR+1))
              echo "v$MAJOR.$MINOR.0" > ./.tag
            elif echo $LAST_COMMIT | grep "\[\(patch\|PATCH\)\]" > /dev/null; then
              PATCH=$((PATCH+1))
              echo "v$MAJOR.$MINOR.$PATCH" > ./.tag
            fi
          else
            if echo $LAST_COMMIT | grep "\[\(major\|MAJOR\)\]" > /dev/null; then
              echo "v1.0.0" > ./.tag
            elif echo $LAST_COMMIT | grep "\[\(minor\|MINOR\)\]" > /dev/null; then
              echo "v0.1.0" > ./.tag
            elif echo $LAST_COMMIT | grep "\[\(patch\|PATCH\)\]" > /dev/null; then
              echo "v0.0.1" > ./.tag
            fi
          fi
          echo "::set-output name=tag::$(cat ./.tag)"
